spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-m2gjj-kr.vpc-pub-cdb.ntruss.com:3306/webproject?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: projectIf
    password: if123!@#


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect


logging:
  level:
    org.hibernate.SQL: debug
